version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: OnlineStore
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OnlineStore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"

